name: 打包
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches:
      - main

jobs:
  run_python_script:
    name: 打包
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      
      - name: Install dependencies
        run: |
          npm i -g pnpm


   
      - name: Navigate to repository directory
        run: cp -r src dist

      - name: Run Python script

        run: |
           pnpm i
      # - name: Build Electron App for windows
      #   if: matrix.os == 'windows-latest'
      #   run: pnpm run build:win 
  
      - name: Build Electron App for macos
        if: matrix.os == 'macos-latest'
        run: |
             pnpm run build



      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: my-package  # 替换为你的软件包名称  # 替换为你的软件包名称
          path: build  # 替换为你的软件包所在的目录名